<a href="https://colab.research.google.com/github/HildiSousa/Desafio-Teste-Ranking/blob/main/TesteETLFinalizado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import pandas as pd
from openpyxl import load_workbook

df_dados = ['/content/Ranking_2023.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas = {
    '/content/Ranking_2023.xlsx': {'AS': (2, 32, 5, 30)}  # Apenas as coordenadas para o último arquivo
}

tabelas = []

for df_dado in df_dados:
    wb = load_workbook(df_dado, data_only=True)
    coordenadas = arquivos_coordenadas[df_dado]
    inicio_linha, fim_linha, inicio_coluna, fim_coluna = coordenadas['AS']
    ws = wb['AS']
    dados_tabela = []
    for row in ws.iter_rows(min_row=inicio_linha, max_row=fim_linha, min_col=inicio_coluna, max_col=fim_coluna):
        linha = [cell.value for cell in row]
        dados_tabela.append(linha)
    df_temp = pd.DataFrame(dados_tabela)
    tabelas.append(df_temp)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas
colunas_extraidas = []
for df_temp in tabelas:
    coluna_0 = df_temp.iloc[:, 0]  # Primeira coluna
    coluna_1 = df_temp.iloc[:, 1]  # Segunda coluna
    ultima_coluna = df_temp.iloc[:, -1]  # Última coluna
    colunas_extraidas.append(pd.concat([coluna_0, coluna_1, ultima_coluna], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset = pd.concat(colunas_extraidas)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset = novo_dataset.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset.xlsx'  # Nome do arquivo
novo_dataset.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')
# Mostrar as primeiras linhas do novo dataset
print(novo_dataset.head())

O arquivo novo_dataset.xlsx foi salvo com sucesso!
         0     1          25
0      None  None          x
2      None  None       2023
4      Acre    AC  16.911177
5   Alagoas    AL   21.38556
6  Amazonas    AM  64.583274

In [89]:

df_dados_2022 = ['/content/Ranking_2022.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2022 = {
    '/content/Ranking_2022.xlsx': {'AS': (2, 32, 5, 29)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2022 = []

for df_dado_2022 in df_dados_2022:
    wb_2022 = load_workbook(df_dado_2022, data_only=True)
    coordenadas_2022 = arquivos_coordenadas_2022[df_dado_2022]
    inicio_linha_2022, fim_linha_2022, inicio_coluna_2022, fim_coluna_2022 = coordenadas_2022['AS']
    ws_2022 = wb_2022['AS']
    dados_tabela_2022 = []
    for row_2022 in ws_2022.iter_rows(min_row=inicio_linha_2022, max_row=fim_linha_2022, min_col=inicio_coluna_2022, max_col=fim_coluna_2022):
        linha_2022 = [cell_2022.value for cell_2022 in row_2022]
        dados_tabela_2022.append(linha_2022)
    df_temp_2022 = pd.DataFrame(dados_tabela_2022)
    tabelas_2022.append(df_temp_2022)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2022
colunas_extraidas_2022 = []
for df_temp_2022 in tabelas_2022:
    coluna_0_2022 = df_temp_2022.iloc[:, 0]  # Primeira coluna
    coluna_1_2022 = df_temp_2022.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2022 = df_temp_2022.iloc[:, -1]  # Última coluna
    colunas_extraidas_2022.append(pd.concat([coluna_0_2022, coluna_1_2022, ultima_coluna_2022], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2022 = pd.concat(colunas_extraidas_2022)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2022 = novo_dataset_2022.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2022.xlsx'  # Nome do arquivo
novo_dataset_2022.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')


# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2022.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2022.xlsx foi salvo com sucesso!
         0     1          24
0      None  None          x
2      None  None       2022
4      Acre    AC          0
5   Alagoas    AL  55.228592
6  Amazonas    AM  45.542456

In [90]:
df_dados_2021 = ['/content/Ranking_2021.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2021 = {
    '/content/Ranking_2021.xlsx': {'AS': (2, 32, 5, 28)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2021 = []

for df_dado_2021 in df_dados_2021:
    wb_2021 = load_workbook(df_dado_2021, data_only=True)
    coordenadas_2021 = arquivos_coordenadas_2021[df_dado_2021]
    inicio_linha_2021, fim_linha_2021, inicio_coluna_2021, fim_coluna_2021 = coordenadas_2021['AS']
    ws_2021 = wb_2021['AS']
    dados_tabela_2021 = []
    for row_2021 in ws_2021.iter_rows(min_row=inicio_linha_2021, max_row=fim_linha_2021, min_col=inicio_coluna_2021, max_col=fim_coluna_2021):
        linha_2021 = [cell_2021.value for cell_2021 in row_2021]
        dados_tabela_2021.append(linha_2021)
    df_temp_2021 = pd.DataFrame(dados_tabela_2021)
    tabelas_2021.append(df_temp_2021)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2021
colunas_extraidas_2021 = []
for df_temp_2021 in tabelas_2021:
    coluna_0_2021 = df_temp_2021.iloc[:, 0]  # Primeira coluna
    coluna_1_2021 = df_temp_2021.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2021 = df_temp_2021.iloc[:, -1]  # Última coluna
    colunas_extraidas_2021.append(pd.concat([coluna_0_2021, coluna_1_2021, ultima_coluna_2021], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2021 = pd.concat(colunas_extraidas_2021)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2021 = novo_dataset_2021.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2021.xlsx'  # Nome do arquivo
novo_dataset_2021.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2021.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2021.xlsx foi salvo com sucesso!
         0     1          23
0      None  None          x
2      None  None       2021
4      Acre    AC  14.037789
5   Alagoas    AL  38.484398
6  Amazonas    AM  42.957814

In [91]:
df_dados_2020 = ['/content/Ranking_2020.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2020 = {
    '/content/Ranking_2020.xlsx': {'AS': (2, 32, 5, 27)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2020 = []

for df_dado_2020 in df_dados_2020:
    wb_2020 = load_workbook(df_dado_2020, data_only=True)
    coordenadas_2020 = arquivos_coordenadas_2020[df_dado_2020]
    inicio_linha_2020, fim_linha_2020, inicio_coluna_2020, fim_coluna_2020 = coordenadas_2020['AS']
    ws_2020 = wb_2020['AS']
    dados_tabela_2020 = []
    for row_2020 in ws_2020.iter_rows(min_row=inicio_linha_2020, max_row=fim_linha_2020, min_col=inicio_coluna_2020, max_col=fim_coluna_2020):
        linha_2020 = [cell_2020.value for cell_2020 in row_2020]
        dados_tabela_2020.append(linha_2020)
    df_temp_2020 = pd.DataFrame(dados_tabela_2020)
    tabelas_2020.append(df_temp_2020)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2020
colunas_extraidas_2020 = []
for df_temp_2020 in tabelas_2020:
    coluna_0_2020 = df_temp_2020.iloc[:, 0]  # Primeira coluna
    coluna_1_2020 = df_temp_2020.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2020 = df_temp_2020.iloc[:, -1]  # Última coluna
    colunas_extraidas_2020.append(pd.concat([coluna_0_2020, coluna_1_2020, ultima_coluna_2020], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2020 = pd.concat(colunas_extraidas_2020)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2020 = novo_dataset_2020.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2020.xlsx'  # Nome do arquivo
novo_dataset_2020.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2020.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2020.xlsx foi salvo com sucesso!
         0     1          22
0      None  None          x
2      None  None       2020
4      Acre    AC  10.984435
5   Alagoas    AL  51.344411
6  Amazonas    AM  48.324435

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

In [92]:
df_dados_2019 = ['/content/Ranking_2019.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2019 = {
    '/content/Ranking_2019.xlsx': {'AS': (2, 32, 5, 26)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2019 = []

for df_dado_2019 in df_dados_2019:
    wb_2019 = load_workbook(df_dado_2019, data_only=True)
    coordenadas_2019 = arquivos_coordenadas_2019[df_dado_2019]
    inicio_linha_2019, fim_linha_2019, inicio_coluna_2019, fim_coluna_2019 = coordenadas_2019['AS']
    ws_2019 = wb_2019['AS']
    dados_tabela_2019 = []
    for row_2019 in ws_2019.iter_rows(min_row=inicio_linha_2019, max_row=fim_linha_2019, min_col=inicio_coluna_2019, max_col=fim_coluna_2019):
        linha_2019 = [cell_2019.value for cell_2019 in row_2019]
        dados_tabela_2019.append(linha_2019)
    df_temp_2019 = pd.DataFrame(dados_tabela_2019)
    tabelas_2019.append(df_temp_2019)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2019
colunas_extraidas_2019 = []
for df_temp_2019 in tabelas_2019:
    coluna_0_2019 = df_temp_2019.iloc[:, 0]  # Primeira coluna
    coluna_1_2019 = df_temp_2019.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2019 = df_temp_2019.iloc[:, -1]  # Última coluna
    colunas_extraidas_2019.append(pd.concat([coluna_0_2019, coluna_1_2019, ultima_coluna_2019], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2019 = pd.concat(colunas_extraidas_2019)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2019 = novo_dataset_2019.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2019.xlsx'  # Nome do arquivo
novo_dataset_2019.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2019.head())

O arquivo novo_dataset_2019.xlsx foi salvo com sucesso!
         0     1          21
0      None  None          x
2      None  None       2019
4      Acre    AC  32.901093
5   Alagoas    AL  44.291417
6  Amazonas    AM  46.320261

In [93]:
df_dados_2018 = ['/content/Ranking_2018.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2018 = {
    '/content/Ranking_2018.xlsx': {'AS': (2, 32, 5, 25)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2018 = []

for df_dado_2018 in df_dados_2018:
    wb_2018 = load_workbook(df_dado_2018, data_only=True)
    coordenadas_2018 = arquivos_coordenadas_2018[df_dado_2018]
    inicio_linha_2018, fim_linha_2018, inicio_coluna_2018, fim_coluna_2018 = coordenadas_2018['AS']
    ws_2018 = wb_2018['AS']
    dados_tabela_2018 = []
    for row_2018 in ws_2018.iter_rows(min_row=inicio_linha_2018, max_row=fim_linha_2018, min_col=inicio_coluna_2018, max_col=fim_coluna_2018):
        linha_2018 = [cell_2018.value for cell_2018 in row_2018]
        dados_tabela_2018.append(linha_2018)
    df_temp_2018 = pd.DataFrame(dados_tabela_2018)
    tabelas_2018.append(df_temp_2018)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2018
colunas_extraidas_2018 = []
for df_temp_2018 in tabelas_2018:
    coluna_0_2018 = df_temp_2018.iloc[:, 0]  # Primeira coluna
    coluna_1_2018 = df_temp_2018.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2018 = df_temp_2018.iloc[:, -1]  # Última coluna
    colunas_extraidas_2018.append(pd.concat([coluna_0_2018, coluna_1_2018, ultima_coluna_2018], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2018 = pd.concat(colunas_extraidas_2018)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2018 = novo_dataset_2018.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2018.xlsx'  # Nome do arquivo
novo_dataset_2018.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2018.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:63: UserWarning: wmf image format is not supported so the image is being dropped
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2018.xlsx foi salvo com sucesso!
         0     1          20
0      None  None          x
2      None  None       2018
4      Acre    AC  38.494684
5   Alagoas    AL  51.373265
6  Amazonas    AM  60.260387

In [94]:
df_dados_2017 = ['/content/Ranking_2017.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2017 = {
    '/content/Ranking_2017.xlsx': {'AS': (2, 32, 5, 24)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2017 = []

for df_dado_2017 in df_dados_2017:
    wb_2017 = load_workbook(df_dado_2017, data_only=True)
    coordenadas_2017 = arquivos_coordenadas_2017[df_dado_2017]
    inicio_linha_2017, fim_linha_2017, inicio_coluna_2017, fim_coluna_2017 = coordenadas_2017['AS']
    ws_2017 = wb_2017['AS']
    dados_tabela_2017 = []
    for row_2017 in ws_2017.iter_rows(min_row=inicio_linha_2017, max_row=fim_linha_2017, min_col=inicio_coluna_2017, max_col=fim_coluna_2017):
        linha_2017 = [cell_2017.value for cell_2017 in row_2017]
        dados_tabela_2017.append(linha_2017)
    df_temp_2017 = pd.DataFrame(dados_tabela_2017)
    tabelas_2017.append(df_temp_2017)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2017
colunas_extraidas_2017 = []
for df_temp_2017 in tabelas_2017:
    coluna_0_2017 = df_temp_2017.iloc[:, 0]  # Primeira coluna
    coluna_1_2017 = df_temp_2017.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2017 = df_temp_2017.iloc[:, -1]  # Última coluna
    colunas_extraidas_2017.append(pd.concat([coluna_0_2017, coluna_1_2017, ultima_coluna_2017], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2017 = pd.concat(colunas_extraidas_2017)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2017 = novo_dataset_2017.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2017.xlsx'  # Nome do arquivo
novo_dataset_2017.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2017.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2017.xlsx foi salvo com sucesso!
         0     1          19
0      None  None          x
2      None  None       2017
4      Acre    AC  41.935717
5   Alagoas    AL  45.012952
6  Amazonas    AM  62.886489

In [95]:
df_dados_2016 = ['/content/Ranking_2016.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2016 = {
    '/content/Ranking_2016.xlsx': {'AS': (2, 32, 5, 23)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2016 = []

for df_dado_2016 in df_dados_2016:
    wb_2016 = load_workbook(df_dado_2016, data_only=True)
    coordenadas_2016 = arquivos_coordenadas_2016[df_dado_2016]
    inicio_linha_2016, fim_linha_2016, inicio_coluna_2016, fim_coluna_2016 = coordenadas_2016['AS']
    ws_2016 = wb_2016['AS']
    dados_tabela_2016 = []
    for row_2016 in ws_2016.iter_rows(min_row=inicio_linha_2016, max_row=fim_linha_2016, min_col=inicio_coluna_2016, max_col=fim_coluna_2016):
        linha_2016 = [cell_2016.value for cell_2016 in row_2016]
        dados_tabela_2016.append(linha_2016)
    df_temp_2016 = pd.DataFrame(dados_tabela_2016)
    tabelas_2016.append(df_temp_2016)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2016
colunas_extraidas_2016 = []
for df_temp_2016 in tabelas_2016:
    coluna_0_2016 = df_temp_2016.iloc[:, 0]  # Primeira coluna
    coluna_1_2016 = df_temp_2016.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2016 = df_temp_2016.iloc[:, -1]  # Última coluna
    colunas_extraidas_2016.append(pd.concat([coluna_0_2016, coluna_1_2016, ultima_coluna_2016], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2016 = pd.concat(colunas_extraidas_2016)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2016 = novo_dataset_2016.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2016.xlsx'  # Nome do arquivo
novo_dataset_2016.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2016.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2016.xlsx foi salvo com sucesso!
         0     1          18
0      None  None          x
2      None  None       2016
4      Acre    AC  31.922562
5   Alagoas    AL  34.353842
6  Amazonas    AM  62.701889

In [96]:
df_dados_2016 = ['/content/Ranking_2016.xlsx']  # Apenas o último arquivo está sendo processado

arquivos_coordenadas_2016 = {
    '/content/Ranking_2016.xlsx': {'AS': (2, 32, 5, 22)}  # Apenas as coordenadas para o último arquivo
}

tabelas_2016 = []

for df_dado_2016 in df_dados_2016:
    wb_2016 = load_workbook(df_dado_2016, data_only=True)
    coordenadas_2016 = arquivos_coordenadas_2016[df_dado_2016]
    inicio_linha_2016, fim_linha_2016, inicio_coluna_2016, fim_coluna_2016 = coordenadas_2016['AS']
    ws_2016 = wb_2016['AS']
    dados_tabela_2016 = []
    for row_2016 in ws_2016.iter_rows(min_row=inicio_linha_2016, max_row=fim_linha_2016, min_col=inicio_coluna_2016, max_col=fim_coluna_2016):
        linha_2016 = [cell_2016.value for cell_2016 in row_2016]
        dados_tabela_2016.append(linha_2016)
    df_temp_2016 = pd.DataFrame(dados_tabela_2016)
    tabelas_2016.append(df_temp_2016)

# Extrair as colunas 0, 1 e a última coluna de cada DataFrame na lista tabelas_2016
colunas_extraidas_2016 = []
for df_temp_2016 in tabelas_2016:
    coluna_0_2016 = df_temp_2016.iloc[:, 0]  # Primeira coluna
    coluna_1_2016 = df_temp_2016.iloc[:, 1]  # Segunda coluna
    ultima_coluna_2016 = df_temp_2016.iloc[:, -1]  # Última coluna
    colunas_extraidas_2016.append(pd.concat([coluna_0_2016, coluna_1_2016, ultima_coluna_2016], axis=1))

# Criar um novo DataFrame com as colunas extraídas
novo_dataset_2016_2 = pd.concat(colunas_extraidas_2016)

# Excluir as linhas 1 e 3 do novo DataFrame
novo_dataset_2016_2 = novo_dataset_2016_2.drop(index=[1, 3])

# Salvar o dataset em um arquivo Excel
nome_arquivo = 'novo_dataset_2016_2.xlsx'  # Nome do arquivo
novo_dataset_2016_2.to_excel(nome_arquivo, index=False)
print(f'O arquivo {nome_arquivo} foi salvo com sucesso!')

# Mostrar as primeiras linhas do novo dataset
print(novo_dataset_2016_2.head())

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

O arquivo novo_dataset_2016_2.xlsx foi salvo com sucesso!
         0     1     17
0      None  None  None
2      None  None  2015
4      Acre    AC     -
5   Alagoas    AL     -
6  Amazonas    AM     -

In [97]:
# Lista para armazenar os DataFrames de todos os arquivos
todos_dataframes = []

# Lista de nomes dos arquivos
nomes_arquivos = ['novo_dataset_2016_2.xlsx', 'novo_dataset_2016.xlsx', 'novo_dataset_2017.xlsx', 'novo_dataset_2018.xlsx', 'novo_dataset_2019.xlsx', 'novo_dataset_2020.xlsx', 'novo_dataset_2021.xlsx', 'novo_dataset_2022.xlsx', 'novo_dataset.xlsx']

# Iterar sobre os nomes dos arquivos e ler cada um deles
for nome_arquivo in nomes_arquivos:
    # Ler o arquivo Excel e armazenar o DataFrame na lista
    df = pd.read_excel(nome_arquivo)
    todos_dataframes.append(df)

# Concatenar todos os DataFrames em um único DataFrame
dataframe_mesclado = pd.concat(todos_dataframes, axis=1)

# Exibir as primeiras linhas do DataFrame mesclado
dataframe_mesclado.head()

,0,1,17,0,1,18,0,1,19,0,...,22,0,1,23,0,1,24,0,1,25
0,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,x,NaN,...,x,NaN,NaN,x,NaN,NaN,x,NaN,NaN,x
1,NaN,NaN,2015,NaN,NaN,2016,NaN,NaN,2017,NaN,...,2020,NaN,NaN,2021,NaN,NaN,2022,NaN,NaN,2023
2,Acre,AC,-,Acre,AC,31.922562,Acre,AC,41.935717,Acre,...,10.984435,Acre,AC,14.037789,Acre,AC,0,Acre,AC,16.911177
3,Alagoas,AL,-,Alagoas,AL,34.353842,Alagoas,AL,45.012952,Alagoas,...,51.344411,Alagoas,AL,38.484398,Alagoas,AL,55.228592,Alagoas,AL,21.38556
4,Amazonas,AM,-,Amazonas,AM,62.701889,Amazonas,AM,62.886489,Amazonas,...,48.324435,Amazonas,AM,42.957814,Amazonas,AM,45.542456,Amazonas,AM,64.583274

In [98]:
dataframe_mesclado

,0,1,17,0,1,18,0,1,19,0,...,22,0,1,23,0,1,24,0,1,25
0,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,x,NaN,...,x,NaN,NaN,x,NaN,NaN,x,NaN,NaN,x
1,NaN,NaN,2015,NaN,NaN,2016,NaN,NaN,2017,NaN,...,2020,NaN,NaN,2021,NaN,NaN,2022,NaN,NaN,2023
2,Acre,AC,-,Acre,AC,31.922562,Acre,AC,41.935717,Acre,...,10.984435,Acre,AC,14.037789,Acre,AC,0,Acre,AC,16.911177
3,Alagoas,AL,-,Alagoas,AL,34.353842,Alagoas,AL,45.012952,Alagoas,...,51.344411,Alagoas,AL,38.484398,Alagoas,AL,55.228592,Alagoas,AL,21.38556
4,Amazonas,AM,-,Amazonas,AM,62.701889,Amazonas,AM,62.886489,Amazonas,...,48.324435,Amazonas,AM,42.957814,Amazonas,AM,45.542456,Amazonas,AM,64.583274
5,Amapá,AP,-,Amapá,AP,41.700226,Amapá,AP,55.362182,Amapá,...,49.793646,Amapá,AP,33.401109,Amapá,AP,34.14609,Amapá,AP,58.164272
6,Bahia,BA,-,Bahia,BA,41.718944,Bahia,BA,50.988532,Bahia,...,62.511209,Bahia,BA,42.490555,Bahia,BA,38.933093,Bahia,BA,24.846405
7,Ceará,CE,-,Ceará,CE,44.134248,Ceará,CE,54.1194,Ceará,...,57.080748,Ceará,CE,44.832286,Ceará,CE,46.983079,Ceará,CE,55.499623
8,Distrito Federal,DF,-,Distrito Federal,DF,73.793978,Distrito Federal,DF,89.217502,Distrito Federal,...,100,Distrito Federal,DF,92.156889,Distrito Federal,DF,87.487279,Distrito Federal,DF,88.597551
9,Espírito Santo,ES,-,Espírito Santo,ES,48.745857,Espírito Santo,ES,56.681422,Espírito Santo,...,78.400157,Espírito Santo,ES,64.554936,Espírito Santo,ES,64.236336,Espírito Santo,ES,75.598189
10,Goiás,GO,-,Goiás,GO,53.386678,Goiás,GO,58.168627,Goiás,...,74.032349,Goiás,GO,60.299117,Goiás,GO,71.607151,Goiás,GO,71.097732
11,Maranhão,MA,-,Maranhão,MA,10.805868,Maranhão,MA,22.652643,Maranhão,...,14.04871,Maranhão,MA,12.212798,Maranhão,MA,6.191355,Maranhão,MA,0
12,Minas Gerais,MG,-,Minas Gerais,MG,47.049349,Minas Gerais,MG,54.333875,Minas Gerais,...,70.22395,Minas Gerais,MG,66.824733,Minas Gerais,MG,65.279882,Minas Gerais,MG,68.565867
13,Mato Grosso do Sul,MS,-,Mato Grosso do Sul,MS,41.897086,Mato Grosso do Sul,MS,51.112049,Mato Grosso do Sul,...,65.726411,Mato Grosso do Sul,MS,53.202036,Mato Grosso do Sul,MS,57.19043,Mato Grosso do Sul,MS,54.886155
14,Mato Grosso,MT,-,Mato Grosso,MT,16.753702,Mato Grosso,MT,18.213919,Mato Grosso,...,45.584041,Mato Grosso,MT,40.113284,Mato Grosso,MT,47.124184,Mato Grosso,MT,52.235908
15,Pará,PA,-,Pará,PA,20.903569,Pará,PA,30.50127,Pará,...,29.732597,Pará,PA,21.038253,Pará,PA,20.5944,Pará,PA,32.088161
16,Paraíba,PB,-,Paraíba,PB,39.941581,Paraíba,PB,51.918197,Paraíba,...,64.931721,Paraíba,PB,39.207482,Paraíba,PB,36.93477,Paraíba,PB,43.813263
17,Pernambuco,PE,-,Pernambuco,PE,39.534221,Pernambuco,PE,57.607881,Pernambuco,...,48.770978,Pernambuco,PE,41.091046,Pernambuco,PE,41.456057,Pernambuco,PE,49.501957
18,Piauí,PI,-,Piauí,PI,20.79254,Piauí,PI,12.351829,Piauí,...,29.833358,Piauí,PI,17.789032,Piauí,PI,19.787435,Piauí,PI,28.626881
19,Paraná,PR,-,Paraná,PR,71.268395,Paraná,PR,77.060026,Paraná,...,84.517225,Paraná,PR,100,Paraná,PR,100,Paraná,PR,100
20,Rio de Janeiro,RJ,-,Rio de Janeiro,RJ,55.407161,Rio de Janeiro,RJ,63.050626,Rio de Janeiro,...,71.47052,Rio de Janeiro,RJ,63.420039,Rio de Janeiro,RJ,67.853102,Rio de Janeiro,RJ,69.787077
21,Rio Grande do Norte,RN,-,Rio Grande do Norte,RN,31.048397,Rio Grande do Norte,RN,47.52465,Rio Grande do Norte,...,51.218462,Rio Grande do Norte,RN,15.492207,Rio Grande do Norte,RN,15.735126,Rio Grande do Norte,RN,19.447907
22,Rondônia,RO,-,Rondônia,RO,14.05898,Rondônia,RO,9.512846,Rondônia,...,0,Rondônia,RO,0,Rondônia,RO,7.282504,Rondônia,RO,13.381733
23,Roraima,RR,-,Roraima,RR,64.227542,Roraima,RR,75.564758,Roraima,...,62.392842,Roraima,RR,13.69113,Roraima,RR,55.12812,Roraima,RR,41.594779
24,Rio Grande do Sul,RS,-,Rio Grande do Sul,RS,39.067943,Rio Grande do Sul,RS,51.182564,Rio Grande do Sul,...,61.51509,Rio Grande do Sul,RS,65.821345,Rio Grande do Sul,RS,69.107485,Rio Grande do Sul,RS,67.735967
25,Santa Catarina,SC,-,Santa Catarina,SC,47.266723,Santa Catarina,SC,55.015948,Santa Catarina,...,66.552211,Santa Catarina,SC,72.575051,Santa Catarina,SC,80.701311,Santa Catarina,SC,72.594712
26,Sergipe,SE,-,Sergipe,SE,34.008205,Sergipe,SE,34.628742,Sergipe,...,42.509358,Sergipe,SE,33.456415,Sergipe,SE,31.143099,Sergipe,SE,14.965106
27,São Paulo,SP,-,São Paulo,SP,62.496593,São Paulo,SP,72.40927,São Paulo,...,93.34513,São Paulo,SP,96.18891,São Paulo,SP,97.856803,São Paulo,SP,89.738397
28,Tocantins,TO,-,Tocantins,TO,27.890173,Tocantins,TO,37.953867,Tocantins,...,45.250809,Tocantins,TO,40.312802,Tocantins,TO,30.269635,Tocantins,TO,26.487148

In [99]:
# Extraindo apenas as colunas de 2015 a 2023 da base de dados final
dataframe_final = dataframe_mesclado.iloc[:, [0,1, 2, 5, 8, 11, 14, 17, 20, 23,26]]

In [100]:
dataframe_final.head()

,0,1,17,18,19,20,21,22,23,24,25
0,NaN,NaN,NaN,x,x,x,x,x,x,x,x
1,NaN,NaN,2015,2016,2017,2018,2019,2020,2021,2022,2023
2,Acre,AC,-,31.922562,41.935717,38.494684,32.901093,10.984435,14.037789,0,16.911177
3,Alagoas,AL,-,34.353842,45.012952,51.373265,44.291417,51.344411,38.484398,55.228592,21.38556
4,Amazonas,AM,-,62.701889,62.886489,60.260387,46.320261,48.324435,42.957814,45.542456,64.583274

In [101]:
dataframe_final.to_excel('/content/Unificado_2015_2023.xlsx', index=False)